commerce_payment.commerce_payment_gateway.plugin.coinify_currency_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    api_key:
      type: string
      label: 'API Key'
    api_secret:
      type: string
      label: 'API Secret'
